### ISSUE TITLE
Don't commit MaxMind license key to your repository

### ISSUE THREAD

**Issue by ugexe** [Torxed/Torxed#1]
https://github.com/Torxed/Torxed/blob/547a75d8cae5633749a02211a0e8ce0c14453152/.filesystem_overlays/archlinux.life/srv/http/vhosts/verify.hvornum.se/vhost.py#L220

**Comment by Torxed** [comment]
Thank you for bringing this up!
I believe this key was generated way way back right around the change to maxmind and I thought that key was deleted after testing. Sadly it looks like I was mistaken as it still works.

I'm aware that it's forever in the git history, this is however not a key that I have access to so I can't revoke it. I'll therefor close this ticket as partially resolved :)

*Edit:* I've been in contact with the maxmind support, however they could not assist me.

**Comment by ugexe** [comment]
Should be deactivated now. Thanks!

**Comment by Torxed** [comment]
Yepp, got a hold of their security department through the support department via chat and they resolved it :) Again, cheers for bringing it to my attention!
